application: tstromberg-sf2sd
version: 1
runtime: go
api_version: go1

handlers:
- url: /third_party
  static_dir: third_party

- url: /themes/(.*)/(.*\.(gif|png|jpg|css))
  static_files: themes/\1/\2
  upload: themes/(.*\.(gif|png|jpg|css))

- url: /.*images/(.*\.(gif|png|jpg))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg))

- url: /admin/.*
  script: _go_app
  login: admin
  auth_fail_action: redirect

- url: /.*
  script: _go_app

